### ISSUE TITLE
Test failing when running locally

### ISSUE THREAD

**Issue by seanfcarroll** [activerecord-hackery/ransack#1023]
Tests are failing when run on local machine. 

```
Failures:

  1) Ransack::Adapters::ActiveRecord::Context#build_correlated_subquery build correlated subquery for Root STI model
     Failure/Error: expect(constraint.left.name).to eql 'person_id'

     NoMethodError:
       undefined method `name' for #<Arel::Nodes::Grouping:0x00007fdcb1510a78>
     # ./spec/ransack/adapters/active_record/context_spec.rb:51:in `block (3 levels) in <module:ActiveRecord>'

  2) Ransack::Adapters::ActiveRecord::Context#build_correlated_subquery build correlated subquery for Child STI model when predicate is not_eq
     Failure/Error: expect(constraint.left.relation.name).to eql 'articles'

     NoMethodError:
       undefined method `relation' for #<Arel::Nodes::Grouping:0x00007fdcb14e7e98>
     # ./spec/ransack/adapters/active_record/context_spec.rb:64:in `block (3 levels) in <module:ActiveRecord>'

  3) Ransack::Adapters::ActiveRecord::Context#build_correlated_subquery build correlated subquery for Child STI model when predicate is eq
     Failure/Error: expect(constraint.left.relation.name).to eql 'articles'

     NoMethodError:
       undefined method `relation' for #<Arel::Nodes::Grouping:0x00007fdcb14d7ef8>
     # ./spec/ransack/adapters/active_record/context_spec.rb:77:in `block (3 levels) in <module:ActiveRecord>'

  4) Ransack::Search#result use appropriate table alias
     Failure/Error:
       expect(real_query)
         .to include "LEFT OUTER JOIN articles ON articles.person_id = people.id"

       expected "SELECT people.* FROM people LEFT OUTER JOIN articles ON ('default_scope' = 'default_scope') AND arti...rent_name_query' AND articles_people.title = 'parents_article_title_query') ORDER BY people.id DESC" to include "LEFT OUTER JOIN articles ON articles.person_id = people.id"
     # ./spec/ransack/search_spec.rb:240:in `block (3 levels) in <module:Ransack>'

Finished in 1.69 seconds (files took 1.11 seconds to load)
350 examples, 4 failures

Failed examples:

rspec ./spec/ransack/adapters/active_record/context_spec.rb:44 # Ransack::Adapters::ActiveRecord::Context#build_correlated_subquery build correlated subquery for Root STI model
rspec ./spec/ransack/adapters/active_record/context_spec.rb:57 # Ransack::Adapters::ActiveRecord::Context#build_correlated_subquery build correlated subquery for Child STI model when predicate is not_eq
```

It seems the 5.2 tests are allowed to fail in Travis. This should be corrected ... I will look into it.

<img width="714" alt="Screenshot 2019-05-17 at 10 07 47" src="https://user-images.githubusercontent.com/11340230/57912868-a5441300-788b-11e9-97cd-451716edbf6b.png">

**Comment by gregmolnar** [comment]
Those are allowed to fail since even minor ActiveRecord releases break Ransack often.

**Comment by seanfcarroll** [comment]
OK, I will try to resolve this. I should have a bit of time to work on Ranack in June.
