### ISSUE TITLE
Polyamorous::JoinDependency: wrong number of arguments (given 4, expected 3)

### ISSUE THREAD

**Issue by 23tux** [activerecord-hackery/ransack#1036]
Gemfile
```
gem "rails", "~> 6.0.0.rc1"
gem "ransack", github: "activerecord-hackery/ransack"
```

When I call ransack on a model
```
Issue.ransack
```

I get this error:
```
wrong number of arguments (given 4, expected 3)
```

The stacktrace leads to this location:
```
alias_tracker = ::ActiveRecord::Associations::AliasTracker.create(self.klass.connection, relation.table.name, join_list)
join_dependency = if ::ActiveRecord::VERSION::STRING >= Constants::RAILS_6_0
  Polyamorous::JoinDependency.new(relation.klass, relation.table, association_joins, Arel::Nodes::OuterJoin)
else
  Polyamorous::JoinDependency.new(relation.klass, relation.table, association_joins)
end

```

```
activerecord (6.0.0.rc1) lib/active_record/associations/join_dependency.rb:67:in `initialize' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/context.rb:285:in `new' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/context.rb:285:in `build_joins' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/context.rb:239:in `join_dependency' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/ransack/context.rb:27:in `initialize' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/context.rb:10:in `initialize' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/ransack/context.rb:11:in `new' 
ransack (e17f1c60a065) lib/ransack/adapters/active_record/ransack/context.rb:11:in `for_class' 
```

**Comment by vrodokanakis** [comment]
See notice in README https://github.com/activerecord-hackery/ransack#rails-6-support and this issue https://github.com/activerecord-hackery/ransack/issues/1032.

Until `rc2` is released If you load Rails 6 from `6-0-stable` branch it will work.

**Comment by seanfcarroll** [comment]
Closed as per message above.
