### ISSUE TITLE
Rails 6 beta error - JoinDependency.new requires 4 arguments (Active Record 6)

### ISSUE THREAD

**Issue by castlese** [activerecord-hackery/ransack#1047]
I've just started a new project with Rails 6.0.0.rc2, ActiveRecord 6.0.0.rc2, ActiveAdmin 2.2.0, Ransack 2.1.1 and get the following error when I try to access one of my controller#index pages in active admin:

```
ArgumentError (wrong number of arguments (given 3, expected 4)):
  
activerecord (6.0.0.rc2) lib/active_record/associations/join_dependency.rb:67:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:264:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:264:in `build_joins'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:219:in `join_dependency'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:27:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:10:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:11:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:11:in `for_class'
ransack (2.1.1) lib/ransack/context.rb:22:in `for'
ransack (2.1.1) lib/ransack/search.rb:25:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/base.rb:18:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/base.rb:18:in `ransack'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `public_send'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `block in method_missing'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:398:in `block in scoping'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:772:in `_scoping'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:398:in `scoping'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `method_missing'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:217:in `apply_filtering'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:59:in `block in find_collection'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:58:in `each'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:58:in `find_collection'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:44:in `collection'
inherited_resources (1.10.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (2.2.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (6.0.0.rc2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0.rc2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/cookies.rb:644:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
activerecord (6.0.0.rc2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
I've traced things back and in new ActiveRecord JoinDependency.new requires 4 arguments  `base`, `table` `associations` & `join_type`. (Ransack is sending in 3: `base`, `table` `associations`)

Rails & Active Record are in beta so I'll probably need to rollback to rails 5.x.x for now to get things working. I'll update as I find out more. Let me know if I should be posting this elsewhere.

**Comment by castlese** [comment]
My bad - just found the closed issue which is duplicate. Closing

**Comment by castlese** [comment]
https://github.com/activerecord-hackery/ransack/issues/1036
