### ISSUE TITLE
wrong number of arguments (given 3, expected 2) in Rails 5.2

### ISSUE THREAD

**Issue by Danissss** [activerecord-hackery/ransack#1091]
Hi, I encounter this issue with `rails 5.2.0`
OS: mac mojave; Ruby version: `2.5.1p57`; 

Sometimes wrong with this function:
```
 class Base
    def dispatch(name, request) #:nodoc:
      set_request!(request)
      process(name)
      to_a
```
Here is full error trace:
```
ArgumentError (wrong number of arguments (given 3, expected 2)):
  
backport_new_renderer (1.0.0) backport_new_renderer.rb:116:in `dispatch'
actionpack (5.2.4) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
oink (0.10.1) lib/oink/middleware.rb:17:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (5.2.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.2.4) lib/rails/engine.rb:524:in `call'
thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.2) lib/thin/connection.rb:84:in `catch'
thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.2) lib/thin/connection.rb:53:in `process'
thin (1.7.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run_machine'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run'
thin (1.7.2) lib/thin/backends/base.rb:73:in `start'
thin (1.7.2) lib/thin/server.rb:162:in `start'
rack (2.0.7) lib/rack/handler/thin.rb:22:in `run'
rack (2.0.7) lib/rack/server.rb:297:in `start'
railties (5.2.4) lib/rails/commands/server/server_command.rb:53:in `start'
railties (5.2.4) lib/rails/commands/server/server_command.rb:147:in `block in perform'
railties (5.2.4) lib/rails/commands/server/server_command.rb:142:in `tap'
railties (5.2.4) lib/rails/commands/server/server_command.rb:142:in `perform'
thor (0.20.3) lib/thor/command.rb:27:in `run'
thor (0.20.3) lib/thor/invocation.rb:126:in `invoke_command'
thor (0.20.3) lib/thor.rb:387:in `dispatch'
railties (5.2.4) lib/rails/command/base.rb:69:in `perform'
railties (5.2.4) lib/rails/command.rb:46:in `invoke'
railties (5.2.4) lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

Here is my Gemfile
```
source 'https://rubygems.org'
ruby '2.5.1'

gem 'rails', '~> 5.2.0'

gem 'mysql2', '<= 0.5.1'
gem 'mini_racer'
gem 'sass-rails'
gem 'coffee-rails'
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'jbuilder_cache_multi'
gem 'sidekiq'
gem 'sinatra', require: false # Required by sidekiq/web
gem 'savon'
gem 'soap4r'
gem 'kaminari'
gem 'actionpack-action_caching'
gem 'acts-as-taggable-on'
gem 'rest-client'
gem 'simple_form'
gem 'responders'
gem 'paperclip'
gem 'whenever', require: false
gem 'typhoeus'
gem 'zip-zip', require: false
gem 'http'
gem 'activeadmin'
gem 'devise'
gem 'redis-rails'
gem 'crack'
gem 'trollop'
gem 'oink'
gem 'backport_new_renderer'
gem 'deep_cloneable'
gem 'gsl'
gem 'kmeans-clusterer'
gem 'scalpel'
gem 'pragmatic_segmenter'
gem 'memory_profiler'
gem 'parallel'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'digest', git: 'git@github.com:ruby/digest.git'
gem 'httparty'
gem 'mail'
gem 'net-ssh'
gem 'highline'

group :development, :test do
  gem 'byebug'
  gem 'web-console'
  gem 'thin'
end

group :development do
  gem 'awesome_print'
  gem "capistrano"
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-sidekiq', require: false
  gem 'binding_of_caller'
  gem 'terminal-notifier-guard', require: false
  gem 'terminal-notifier', require: false
  gem 'derailed_benchmarks'
  gem 'stackprof' # used by derailed_benchmarks
end
```

**Comment by seanfcarroll** [comment]
Can you add the code used to call Ransack and your model?

**Comment by Danissss** [comment]
I moved to Rails 4.2.0.  Not sure why this happens with 5.2
