### ISSUE TITLE
NoMethodError error when using `ransackable_scopes` and `date_field`

### ISSUE THREAD

**Issue by kenzo-tanaka** [activerecord-hackery/ransack#1252]
Hello. First of all, thank you for creating such a nice library!
I would like to report that I encountered an error with `ransackable_scopes` in my project.

## Version

- ransack 2.4.2
- Rails 6.1.4.1
- Ruby 2.6.3p62

## Reproduction

- Create a scope that takes a date type as an argument, and set it to `ransackable_scopes`.
  ```rb
  # article.rb

  class Article < ApplicationRecord
    scope :created_since, -> (date) {
      where('created_at >= ?', date)
    }

    def self.ransackable_scopes(auth_object = nil)
      %i[created_since]
    end
  end
  ```
  ```rb
  # search_controller.rb
  class SearchController < ApplicationController
    def index
      @q = Article.ransack(params[:q])
    end
  end
  ```
- Add a `date_field` using this scope in view.
  ```slim
  = search_form_for @q, url: search_index_path do |form|
    = form.date_field :created_since
    = form.submit 'Search'
  ```
  ![スクリーンショット 2021-09-25 10 18 59](https://user-images.githubusercontent.com/33926355/134753033-f910a94e-c9ca-47e7-b19d-4aaab71ae721.png)
- NoMethodError error occurs when submitting the search form.
  ```
  undefined method `strftime' for "2021-09-25":String
  Did you mean?  strip
  ```
  ```
  # full trace
  actionview (6.1.4.1) lib/action_view/helpers/tags/date_field.rb:9:in `format_date'
  actionview (6.1.4.1) lib/action_view/helpers/tags/datetime_field.rb:9:in `render'
  actionview (6.1.4.1) lib/action_view/helpers/form_helper.rb:1400:in `date_field'
  app/views/search/index.html.slim:4
  actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
  actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
  actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
  actionview (6.1.4.1) lib/action_view/helpers/form_helper.rb:450:in `form_for'
  client_side_validations (18.0.0) lib/client_side_validations/action_view/form_helper.rb:11:in `form_for'
  ransack (2.4.2) lib/ransack/helpers/form_helper.rb:34:in `search_form_for'
  app/views/search/index.html.slim:3
  ```

I have checked this behavior in the repository here.
[ransackable_scopes by kenzo-tanaka · Pull Request #12 · kenzo-tanaka/rails_sandbox](https://github.com/kenzo-tanaka/rails_sandbox/pull/12)

I added the scope to `ransackable_scopes_skip_sanitize_args`, but it doesn't work. (Raise same error)

```rb
# app/models/article.rb
def self.ransackable_scopes_skip_sanitize_args
  %i[created_since]
end
```

I'm sorry if I misunderstood.

**Comment by kenzo-tanaka** [comment]
Sorry, it works with `search_field`.
