### ISSUE TITLE
undefined method `strip_whitespace=' for Ransack:Module (NoMethodError)

### ISSUE THREAD

**Issue by GarrisonD** [activerecord-hackery/ransack#1260]
Are you sure the latest version of `Ransack` is deployed to `RubyGems` properly?

```
/usr/src/app/config/initializers/ransack.rb:2:in `block in <main>': undefined method `strip_whitespace=' for Ransack:Module (NoMethodError)
        from /usr/local/bundle/gems/ransack-2.4.2/lib/ransack/configuration.rb:41:in `configure'
        from /usr/src/app/config/initializers/ransack.rb:1:in `<main>'
```

**Comment by GarrisonD** [comment]
I see, this configuration flag hasn't been released yet - it presents only in `master` branch.

Guys, what are you waiting for? 🙂

**Comment by deivid-rodriguez** [comment]
I guess this should be present in Ransack 2.5.0, so I'll close this.
