### ISSUE TITLE
Arguments passed to url_for can't be handled. Please require routes or provide your own implementation

### ISSUE THREAD

**Issue by ferminmoli** [activerecord-hackery/ransack#1282]
Hi! I am having this issue. I am combining pagy gem with ransack gem

rails - 5.2.1
pagy - 5.10
ransack - 2.3.2

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10004370/157684271-b5b99235-3fad-44bd-baf1-11906d634f49.png">

Could someone help me to figure out what's happening?

**index.html.erb**
```
<h1>Players</h1>
<br>

<%= search_form_for @q, :html => {:class => "form-inline"} do |f| %>
  <div class="form-group">
    <%= f.label "Search: ", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.search_field :last_name_cont, class: "form-control" %>
    </div>
  </div>
  <%= f.submit class: "btn btn-success" %>
<% end %>
 
<%= sort_link(@q, :last_name) %>
<br>
<table id="players" class="table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>Last name</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each.with_index do |player, i| %>
      <tr>
        <td><%= player.id%></td>
        <td><%= player.last_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %> 
```

**players_controller.rb**
```
class PlayersController < ApplicationController

  # GET /players
  # GET /players.json
  def index
    @q = Player.ransack(params[:q])
    @pagy, @players = pagy(@q.result)
  end
end
```

**Stack trace**
```
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/helpers/url_helper.rb:41:in `url_for'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/ransack-2.3.2/lib/ransack/helpers/form_helper.rb:94:in `url'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/ransack-2.3.2/lib/ransack/helpers/form_helper.rb:54:in `sort_link'](http://localhost:4000/players?page=3#)
[app/views/players/index.html.erb:18:in `_app_views_players_index_html_erb__4203801862734142286_120820'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/template.rb:159:in `block in render'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/template.rb:354:in `instrument_render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/template.rb:157:in `render'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:16:in `render'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:44:in `render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:25:in `render'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:103:in `_render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:84:in `render_to_body'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'](http://localhost:4000/players?page=3#)
[vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.1/lib/abstract_controller/rendering.rb:25:in `render'](http://localhost:4000/players?page=3#)
```

**Comment by deivid-rodriguez** [comment]
Please upgrade ransack before reporting an issue!

**Comment by ferminmoli** [comment]
I am still having the same issue on ransack 2.6.0 combined with rails 6. thoughts?

![image](https://user-images.githubusercontent.com/10004370/157690630-3cffe190-989e-471b-a348-cd5ab004293e.png)
![image](https://user-images.githubusercontent.com/10004370/157690691-19cddd0b-c338-4505-bb80-e288e2314c1b.png)

**Comment by deivid-rodriguez** [comment]
Thanks! Can you provide a sample application that reproduces the problem?
