### ISSUE TITLE
sqlite3 errors in CI

### ISSUE THREAD

**Issue by scarroll32** [activerecord-hackery/ransack#1489]
The CI is failing on a sqlite error, eg [like this](https://github.com/activerecord-hackery/ransack/actions/runs/8854252210/job/24316914450)

Any help on this by the community would be appreciated.

```
LoadError:
  Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.
```

**Comment by scarroll32** [comment]
Something is requiring sqlite3 at 1.4, even though it's installed as 2.0.1

```
    sqlite3 (2.0.1-aarch64-linux-gnu)
    sqlite3 (2.0.1-aarch64-linux-musl)
    sqlite3 (2.0.1-arm-linux-gnu)
    sqlite3 (2.0.1-arm-linux-musl)
    sqlite3 (2.0.1-arm64-darwin)
    sqlite3 (2.0.1-x86-linux-gnu)
    sqlite3 (2.0.1-x86-linux-musl)
    sqlite3 (2.0.1-x86_64-darwin)
    sqlite3 (2.0.1-x86_64-linux-gnu)
    sqlite3 (2.0.1-x86_64-linux-musl)
```

```
LoadError:
  Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? Could not find 'sqlite3' (~> 1.4) - did find: [sqlite3-2.0.1-x86_64-darwin]
  Checked in 'GEM_PATH=/Users/sean/.gem/ruby/3.2.0:/Users/sean/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0' , execute `gem env` for more information
# ./spec/support/schema.rb:25:in `<top (required)>'
# ./spec/spec_helper.rb:18:in `block in <top (required)>'
# ./spec/spec_helper.rb:18:in `each'
# ./spec/spec_helper.rb:18:in `<top (required)>'
# ./spec/ransack/search_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# Gem::MissingSpecVersionError:
#   Could not find 'sqlite3' (~> 1.4) - did find: [sqlite3-2.0.1-x86_64-darwin]
#   Checked in 'GEM_PATH=/Users/sean/.gem/ruby/3.2.0:/Users/sean/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0' , execute `gem env` for more information
#   ./spec/support/schema.rb:25:in `<top (required)>'
```

**Comment by andxyz** [comment]
@scarroll32 Looks like there is a fix in main branch of rails/rails for this
See this PR https://github.com/rails/rails/pull/51592

I think you are waiting for them to cut a release since this fix is only in main for now.
