### ISSUE TITLE
NoMethodError error with_connection with Rails 7.2

### ISSUE THREAD

**Issue by KojiTsuchiya-Ruby** [activerecord-hackery/ransack#1495]
Ransack: 4.4.1
Rails: 7.2.0.beta1
Ruby: 3.1.4
MySQL: 8.0.31

This is the error we got:
``` ruby
NoMethodError:
       undefined method `with_connection' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0000763d2cd984d0 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x0000763d2cd98160 @stack=[#<ActiveRecord::ConnectionAdapters::RealTransaction:0x0000763d237058b0 @callbacks=nil, @connection=#<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0000763d2cd984d0 ...>,

                pool.with_connection do |connection|
                    ^^^^^^^^^^^^^^^^
        Did you mean?  raw_connection
      # /usr/local/bundle/gems/activerecord-7.2.0.beta1/lib/active_record/associations/alias_tracker.rb:10:in `create'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/adapters/active_record/context.rb:281:in `build_joins'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/adapters/active_record/context.rb:249:in `join_dependency'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/context.rb:40:in `initialize'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/context.rb:13:in `new'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/context.rb:13:in `for_class'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/context.rb:27:in `for'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/search.rb:32:in `initialize'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/adapters/active_record/base.rb:16:in `new'
      # /usr/local/bundle/gems/ransack-4.1.1/lib/ransack/adapters/active_record/base.rb:16:in `ransack'
      # /usr/local/bundle/gems/activerecord-7.2.0.beta1/lib/active_record/relation/delegation.rb:78:in `block in ransack'
      # /usr/local/bundle/gems/activerecord-7.2.0.beta1/lib/active_record/relation.rb:1355:in `_scoping'
      # /usr/local/bundle/gems/activerecord-7.2.0.beta1/lib/active_record/relation.rb:541:in `scoping'
      # /usr/local/bundle/gems/activerecord-7.2.0.beta1/lib/active_record/relation/delegation.rb:78:in `ransack'
```

**Comment by KojiTsuchiya-Ruby** [comment]
I have confirmed that this issue will be addressed by this pull request:
[PR Link](https://github.com/activerecord-hackery/ransack/pull/1493)

Do you have plans to merge this pull request?

**Comment by tagliala** [comment]
Hi, this is a duplicate of #1491 (with a better title for google searches)

**Comment by KojiTsuchiya-Ruby** [comment]
Thank you for letting me know. I'll follow up on issue #1491 for further updates. The issue I posted will be closed.
