### ISSUE TITLE
1.6.x: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by nateberkopec** [activerecord-hackery/ransack#496]
I think 1.6.0 broke multiparameter attributes like dates. Given a form like: 

```
 <%= f.date_select :start_time_gteq %>
```

...where start_time is a DateTime, it looks like collapse_multiparameter_attributes tries to modify a hash in an iteration. I believe this was introduced by https://github.com/activerecord-hackery/ransack/commit/ee571fe9a2d729adc641528a9b65d0cebf4f84ba.

Here's the relevant stacktrace lines:

```
active_support/hash_with_indifferent_access.rb:97:in `[]='
    regular_writer(convert_key(key), convert_value(value, for: :assignment))
  active_support/hash_with_indifferent_access.rb:97:in `[]='
    regular_writer(convert_key(key), convert_value(value, for: :assignment))
  ransack/search.rb:167:in `block in collapse_multiparameter_attributes!'
    attrs[real_attribute] ||= []
  ransack/search.rb:156:in `each_key'
    attrs.each_key do |k|
  ransack/search.rb:156:in `collapse_multiparameter_attributes!'
    attrs.each_key do |k|
  ransack/search.rb:47:in `build'
    collapse_multiparameter_attributes!(params).each do |key, value|
  ransack/search.rb:39:in `initialize'
    build(params.with_indifferent_access)
```

**Comment by jonatack** [comment]
Thank you. You are correct. Because in-place mutation. Reverted.

**Comment by jonatack** [comment]
Test added and change log updated. Thanks again @nateberkopec :smiley:

**Comment by nateberkopec** [comment]
(thumbsup)!
