### ISSUE TITLE
ArgumentError: Don't know what context to use for

### ISSUE THREAD

**Issue by murtyk** [activerecord-hackery/ransack#511]
Searched issues and SO but not able to find any information to address this issue.
    
gemfile.lock:

     rails (4.0.5)
      actionmailer (= 4.0.5)
      actionpack (= 4.0.5)
      activerecord (= 4.0.5)
      activesupport (= 4.0.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.5)
      sprockets-rails (~> 2.0.0)
    ransack (1.6.3)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)

    $ rails c
    Loading development environment (Rails 4.0.5)
    2.1.3 :001 > Account.ransackable_attributes
     => ["id", "name", "description", "client_type", "status", "subdomain", "logo_file", "created_at", "updated_at", "options"] 
    2.1.3 :002 > Account.ransack
    ArgumentError: Don't know what context to use for Account
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/ransack-1.6.3/lib/ransack/context.rb:30:in `for'
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/ransack-1.6.3/lib/ransack/search.rb:32:in `initialize'
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/ransack-1.6.3/lib/ransack/adapters/active_record/base.rb:15:in `new'
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/ransack-1.6.3/lib/ransack/adapters/active_record/base.rb:15:in `ransack'
      from (irb):2
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
      from /home/murtykorada/.rvm/gems/ruby-2.1.3/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
      from bin/rails:4:in `require'
      from bin/rails:4:in `<main>'
    2.1.3 :003 >

**Comment by murtyk** [comment]
sorry, I was hasty. Should have read the documents more thoroughly.

gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'rails-4'

solved the problem.
