### ISSUE TITLE
Scopes broken on Rails 4.2 branch

### ISSUE THREAD

**Issue by davidlesches** [activerecord-hackery/ransack#528]
On the Rails 4.2 branch you cannot search by scopes.

A simple example.

```
class User
  scope :active, -> { where(is_active: true) }
  def self.ransackable_scopes(auth_object = nil)
    [:active]
  end
end
```

```
User.search(active: true)
```

Returns:

```
undefined method `scope_arity' for #<Ransack::Adapters::ActiveRecord::Context:0x007fadb12650f0>
# from: lib/ransack/search.rb:124:in `add_scope'
```

Any ideas on how to solve this?

**Comment by xinlangzi** [comment]
A simple example with scope:
```
class User < ActiveRecord::Base
  scope :inactive, ->(value){
    where.not(deleted_at: nil) if value=='t'
  }

  def self.ransackable_scopes(auth_object = nil)
    [:inactive]
  end

end
```
Then I called:

```
User.search(inactive: 'true').result.to_sql
```

Got eorror:

```
ArgumentError: wrong number of arguments (0 for 1)
```

**Comment by davidlesches** [comment]
Your scope is incorrect, should be simply -

```ruby
scope :inactive, -> { where.not(deleted_at: nil) }
```

**Comment by davidlesches** [comment]
For anyone else in the future who stumbles on this issue, the `undefined method `scope_arity'` problem is caused because the 4.2 branch is missing the code that handles scopes.

You can fix this by patching. Add this to a Rails initializer.

```ruby
module Ransack
  class Context

    def scope_arity(scope)
      @klass.method(scope).arity
    end

    def chain_scope(scope, args)
      return unless @klass.method(scope) && args != false
      @object = if scope_arity(scope) < 1 && args == true
        @object.public_send(scope)
      else
        @object.public_send(scope, *args)
      end
    end

  end
end
```

**Comment by xinlangzi** [comment]
@davidlesches 

I intentionally made the scope with parameter. So I can use the checkbox on the search_form_for.

**Comment by davidlesches** [comment]
@xinlangzi take it out; it's not needed. Create the scope the way I made it above, and then, using Ransack, you can use .search(is_inactive: true) of (is_inactive: false).

Even in the form you can create the field :is_inactive, it automaps to the inactive scope. There is no need to pass a parameter into the actual scope.

**Comment by xinlangzi** [comment]
@davidlesches 

WOW. Thank you, I think it is a new change. :) Wonderful. I like it.

**Comment by xinlangzi** [comment]
@davidlesches 

Sorry, I tried your idea. It does not work well. Also very interesting thing happen to me:

```
scope :inactive, ->(value){
    only_deleted if value.to_boolean
}

pry(main)>  Company.search(inactive: 'true').result.to_sql
ArgumentError: wrong number of arguments (0 for 1)
from /Users/xinlangzi/workspace/journey/app/models/company.rb:25:in `block in <class:Company>'
```

But this following scope works well:
```
scope :tags, ->(tags){
   tagged_with(tags.split(',').map(&:strip)) if tags.present?
}

pry(main)> Company.search(tags: 'Hello').result.to_sql
  ActsAsTaggableOn::Tag Load (0.3ms)  SELECT "tags".* FROM "tags" WHERE (LOWER(name) = LOWER('hello'))
=> "SELECT \"companies\".* FROM \"companies\" WHERE \"companies\".\"deleted_at\" IS NULL AND (1 = 0)  ORDER BY name asc"
```

Then I updated the scope inactive to

```
scope :inactive, ->(value='t'){
  only_deleted if value.to_boolean
}

pry(main)> Company.search(inactive: 't').result.to_sql
=> "SELECT \"companies\".* FROM \"companies\" WHERE (\"companies\".\"deleted_at\" IS NOT NULL)  ORDER BY name asc"

pry(main)> Company.search(inactive: 'f').result.to_sql
=> "SELECT \"companies\".* FROM \"companies\" WHERE \"companies\".\"deleted_at\" IS NULL  ORDER BY name asc"
```

**Comment by davidlesches** [comment]
What do you mean by "It does not work well", what happened?

**Comment by xinlangzi** [comment]
@davidlesches 


```
  scope :inactive, ->{
    where.not(deleted_at: nil)
  }
```

See the following SQL generated by ransack. They are the same.
```
[20] pry(main)> Company.search(is_inactive: true).result.to_sql
=> "SELECT \"companies\".* FROM \"companies\" WHERE \"companies\".\"deleted_at\" IS NULL  ORDER BY name asc"
[21] pry(main)> Company.search(is_inactive: false).result.to_sql
=> "SELECT \"companies\".* FROM \"companies\" WHERE \"companies\".\"deleted_at\" IS NULL  ORDER BY name asc"
```

**Comment by davidlesches** [comment]
Ah I see. OK

**Comment by jonatack** [comment]
Closing due to inactivity and the Ransack `rails-4.2` branch is not maintained. The last officially-released version and the master branch are maintained. Cheers.
