### ISSUE TITLE
undefined method sort_link

### ISSUE THREAD

**Issue by xinlangzi** [activerecord-hackery/ransack#565]
I use the sort_link inside the view, but I got the following error:

Environment:
```
ruby 2.1.5 and rails 4.1.12
```

Exception:
```
NoMethodError - undefined method `sort_link' for #<#<Class:0x007f86cb77c898>:0x000001100cc360>:
  app/views/companies/_filter.html.slim:9:in `_app_views_companies__filter_html_slim___4470079552345303652_2282975960'
  actionview (4.1.12) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.12) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.12) lib/action_view/template.rb:143:in `render'
  actionview (4.1.12) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  actionview (4.1.12) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  actionview (4.1.12) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.12) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.12) lib/action_view/renderer/partial_renderer.rb:278:in `render'
  actionview (4.1.12) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.1.12) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  app/views/companies/index.html.slim:7:in `_app_views_companies_index_html_slim___1027275559075042477_70108457970620'
  actionview (4.1.12) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.12) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.12) lib/action_view/template.rb:143:in `render'
  actionview (4.1.12) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.12) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.12) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.12) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.12) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.12) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.12) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.12) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.12) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.12) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.12) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.12) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.12) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.12) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.12) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.12) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.1.12) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/xinlangzi/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.12) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.1.12) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wisepdf (1.4.0) lib/wisepdf/render.rb:21:in `render_with_wisepdf'
  app/controllers/companies_controller.rb:19:in `block (2 levels) in index'
  actionpack (4.1.12) lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
  app/controllers/companies_controller.rb:16:in `index'
  actionpack (4.1.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.12) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.12) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.12) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.12) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.12) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.12) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.12) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.12) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.12) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.12) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.12) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.12) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:692:in `call'
  meta_request (0.2.1) lib/meta_request/middlewares/app_request_handler.rb:11:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.2.1) lib/meta_request/middlewares/headers.rb:16:in `call'
  meta_request (0.2.1) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.12) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.12) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  airbrake (4.3.0) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.12) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.12) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.12) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.1.12) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  airbrake (4.3.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.3.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.1.12) lib/rails/engine.rb:514:in `call'
  railties (4.1.12) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.1.12) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.12) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.12) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.12) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.12) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `<main>'
```

**Comment by jonatack** [comment]
This doesn't look like a bug in Ransack. I'm closing this for the moment as we don't really have much more to go on at this point - if you have more information (a gist of code, etc.) that points to a problem in Ransack then I'll be happy to re-open the issue. Thanks.
