### ISSUE TITLE
sort_link fails

### ISSUE THREAD

**Issue by rockandruby** [activerecord-hackery/ransack#746]
I'm writing rails engine(rails 5), postgresql, ruby 2.3.1, ransack 1.8.2. No additional gems are used.
I'm trying to do sorting link in table. Here's my code:

**CONTROLLER:**
`def index

      @q = @model.ransack(params[:q])
      @entities = @q.result.select(select_fields('list'))

 end`

**VIEW**
`%table.table

    %thead

      - @config['attributes']['list'].each do |attr|

        %th= sort_link @q, attr.to_sym, attr.upcase`

Ang I get the following error:
`No route matches {:action=>"index", :controller=>"adminka/posts", :q=>{"s"=>"title asc"}}
Extracted source (around line #50): 
        message << " missing required keys: #{missing_keys.sort.inspect}" if missing_keys && !missing_keys.empty?

        raise ActionController::UrlGenerationError, message
      end

      def clear

Rails.root: /var/www/adminka/test/dummy

Application Trace | Framework Trace | Full Trace
actionpack (5.0.0.1) lib/action_dispatch/journey/formatter.rb:50:in `generate'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:629:in `generate'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:660:in `generate'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:707:in `url_for'
actionpack (5.0.0.1) lib/action_dispatch/routing/url_for.rb:172:in `url_for'
actionview (5.0.0.1) lib/action_view/routing_url_for.rb:90:in `url_for'
ransack (1.8.2) lib/ransack/helpers/form_helper.rb:94:in `url'
ransack (1.8.2) lib/ransack/helpers/form_helper.rb:54:in `sort_link'
/var/www/adminka/app/views/adminka/crud/index.html.haml:6:in `block in __var_www_adminka_app_views_adminka_crud_index_html_haml___2114439020815314662_32426800'
/var/www/adminka/app/views/adminka/crud/index.html.haml:5:in `each'
/var/www/adminka/app/views/adminka/crud/index.html.haml:5:in `__var_www_adminka_app_views_adminka_crud_index_html_haml___2114439020815314662_32426800'`

**Comment by rockandruby** [comment]
Sorry, was my fault. I should pass routes from main app to engine
