### ISSUE TITLE
undefined method for Ransack::Search<class base: Grouping <combinator: and>>:Ransack::Search

### ISSUE THREAD

**Issue by deemytch** [activerecord-hackery/ransack#758]
Ransack is used inside ActiveAdmin, git master
Rails 4.2.7.1
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

I have the class User with second-level scope with condition.
<pre>class User
...
  has_many :wallets, :inverse_of => :user, :dependent => :destroy
    has_many :money_in, -> { where money_in: true }, :through => :wallets, :source => :money_in_outs</pre>

after generating the needed scaffold class for activeadmin I have at :3001/admin/users
<pre> Showing ...vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/app/views/active_admin/resource/index.html.arb where line #2 raised:

undefined method `money_in' for Ransack::Search<class: Client, base: Grouping <combinator: and>>:Ransack::Search
</pre>

With my simple classes, where I don't have such complex logic - there all is ok.

Full dump: <pre>
NoMethodError in Admin::Clients#index

Showing ...vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/app/views/active_admin/resource/index.html.arb where line #2 raised:

undefined method `money_in' for Ransack::Search<class: User, base: Grouping <combinator: and>>:Ransack::Search

Extracted source (around line #106):

104        end
105      else
106        super
107      end
108    end

Rails.root: ...
Application Trace | Framework Trace | Full Trace

vendor/bundle/ruby/2.4.0/bundler/gems/ransack-4adfd103983c/lib/ransack/search.rb:106:in `method_missing'
vendor/bundle/ruby/2.4.0/bundler/gems/ransack-4adfd103983c/lib/ransack/helpers/form_builder.rb:10:in `value'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/tags/select.rb:16:in `block in render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/tags/select.rb:16:in `fetch'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/tags/select.rb:16:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/form_options_helper.rb:163:in `select'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/form_options_helper.rb:777:in `select'
vendor/bundle/ruby/2.4.0/gems/formtastic-3.1.4/lib/formtastic/inputs/select_input.rb:173:in `select_html'
vendor/bundle/ruby/2.4.0/gems/formtastic-3.1.4/lib/formtastic/inputs/select_input.rb:168:in `block in to_html'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:38:in `capture'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/inputs/filters/base.rb:12:in `input_wrapping'
vendor/bundle/ruby/2.4.0/gems/formtastic-3.1.4/lib/formtastic/inputs/select_input.rb:166:in `to_html'
vendor/bundle/ruby/2.4.0/gems/formtastic-3.1.4/lib/formtastic/helpers/input_helper.rb:242:in `input'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/forms.rb:14:in `filter'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/forms.rb:62:in `block (2 levels) in active_admin_filters_form_for'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/forms.rb:58:in `each'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/forms.rb:58:in `block in active_admin_filters_form_for'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/capture_helper.rb:38:in `capture'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/helpers/form_helper.rb:444:in `form_for'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
vendor/bundle/ruby/2.4.0/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/forms.rb:57:in `active_admin_filters_form_for'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element.rb:180:in `method_missing'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/filters/resource_extension.rb:155:in `block in filters_sidebar_section'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/components/sidebar_section.rb:25:in `instance_exec'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/components/sidebar_section.rb:25:in `build_sidebar_content'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/components/sidebar_section.rb:13:in `build'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `sidebar_section'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:130:in `block (2 levels) in build_sidebar'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:129:in `collect'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:129:in `block in build_sidebar'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:128:in `build_sidebar'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:76:in `block in build_page_content'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:74:in `build_page_content'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:52:in `block (2 levels) in build_page'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:48:in `block in build_page'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:47:in `build_page'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/views/pages/base.rb:10:in `build'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/app/views/active_admin/resource/index.html.arb:2:in `block in _vendor_bundle_ruby_______bundler_gems_activeadmin_____e_b___b__app_views_active_admin_resource_index_html_arb___2861251190679489977_36541340'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:45:in `instance_eval'
vendor/bundle/ruby/2.4.0/gems/arbre-1.1.1/lib/arbre/context.rb:45:in `initialize'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/app/views/active_admin/resource/index.html.arb:1:in `new'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/app/views/active_admin/resource/index.html.arb:1:in `_vendor_bundle_ruby_______bundler_gems_activeadmin_____e_b___b__app_views_active_admin_resource_index_html_arb___2861251190679489977_36541340'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/template.rb:333:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/template_renderer.rb:14:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/renderer.rb:46:in `render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/renderer/renderer.rb:27:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/rendering.rb:100:in `_render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/streaming.rb:217:in `_render_template'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/rendering.rb:83:in `render_to_body'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/abstract_controller/rendering.rb:25:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `ms'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activerecord/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `render'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/action_controller/responder.rb:238:in `default_render'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/action_controller/responder.rb:170:in `to_html'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/responders/flash_responder.rb:107:in `to_html'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/action_controller/responder.rb:163:in `respond'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/action_controller/responder.rb:156:in `call'
vendor/bundle/ruby/2.4.0/gems/responders-2.3.0/lib/action_controller/respond_with.rb:205:in `respond_with'
vendor/bundle/ruby/2.4.0/gems/inherited_resources-1.7.0/lib/inherited_resources/actions.rb:7:in `index'
vendor/bundle/ruby/2.4.0/bundler/gems/activeadmin-6463e2b717b2/lib/active_admin/resource_controller/streaming.rb:12:in `index'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/abstract_controller/base.rb:198:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:117:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:505:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/abstract_controller/base.rb:137:in `process'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionview/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_controller/metal.rb:237:in `block in action'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/routing/route_set.rb:817:in `call'
vendor/bundle/ruby/2.4.0/gems/bullet-5.5.0/lib/bullet/rack.rb:10:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activerecord/lib/active_record/query_cache.rb:36:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activerecord/lib/active_record/migration.rb:377:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/reloader.rb:73:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/rack/logger.rb:22:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/actionpack/lib/action_dispatch/middleware/static.rb:120:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/handler/thin.rb:19:in `run'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/server.rb:286:in `start'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/server.rb:80:in `start'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:80:in `block in server'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:75:in `tap'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:75:in `server'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
vendor/bundle/ruby/2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Request

Parameters:

None

Toggle session dump

_csrf_token: "knrkCBaXikcoVBLPvPDp8B8gfqPr/tjp46Zw1KAMMbw="
expires: "2017-02-01T14:30:13.774+02:00"
session_id: "370443c8a3f69e942da1e2b35047f3ed"

Toggle env dump

GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "ru-RU,ru;q=0.9,uk;q=0.7,fr;q=0.6,he;q=0.4,en-US;q=0.3,en;q=0.1"
HTTP_CACHE_CONTROL: "max-age=0"
REMOTE_ADDR: "192.168.35.254"
SERVER_NAME: "192.168.35.254"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None

</pre>

**Comment by scarroll32** [comment]
Stale and spam
