### ISSUE TITLE
undefined method `join_root' for :item_type:Symbol for negative cont

### ISSUE THREAD

**Issue by mfazekas** [activerecord-hackery/ransack#770]
Run this script to reproduce
https://gist.github.com/mfazekas/4e2f78ebe295b4e20ff7962ba7555d80

Issue seems to be in 
https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/context.rb#L151

`joins_values` returns a `Symbol` which has no `join_root`

```sh
NoMethodError: undefined method `join_root' for :item_type:Symbol
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/context.rb:152:in `block in remove_association'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/context.rb:151:in `delete_if'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/context.rb:151:in `remove_association'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:11:in `block in arel_predicate'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:6:in `map'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:6:in `arel_predicate'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:17:in `visit_Ransack_Nodes_Condition'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:52:in `visit'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:5:in `accept'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `block in visit_and'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `map'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `visit_and'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:24:in `visit_Ransack_Nodes_Grouping'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:52:in `visit'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/visitor.rb:5:in `accept'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/adapters/active_record/context.rb:37:in `evaluate'
    /Users/boga/.rvm/gems/ruby-2.3.1/bundler/gems/ransack-8ca8c95c6543/lib/ransack/search.rb:36:in `result'
    ./test-ransack-join.rb:83:in `test_parent_item_info_name'
```

**Comment by dbridges** [comment]
@mfazekas Did you ever figure out a workaround for this?
