### ISSUE TITLE
There was an error while trying to load the gem 'ransack'. (Bundler::GemRequireError) Gem Load Error is: undefined method `require_constants' for nil:NilClass

### ISSUE THREAD

**Issue by kul1** [activerecord-hackery/ransack#890]
Running in Ruby 2.4.1, Rails 5.1.4, 5.1.5
Created with Rails New myapp -B -O -T (with mongoid)
Error:
There was an error while trying to load the gem 'ransack'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `require_constants' for nil:NilClass

**Comment by seanfcarroll** [comment]
That part of the code has been stable for 2 years ... 
https://github.com/activerecord-hackery/ransack/blame/7557c12a1395ced0d993b597730ebd04fd0604ee/lib/ransack.rb

I don't quite understand how you are getting a Ransack error on rails new -- the Gemfile would not be created right?

**Comment by kul1** [comment]
my gemfile created by rails new myapp -B -O -T
Here my gemfile:
I only add gem 'ransack'
then bundle install
and 
rails s
shown error  next following:


```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'ransack'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.5'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```



=======
Error output:
```
rails s
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ransack'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `require_constants' for nil:NilClass
Backtrace for gem load error is:
/Users/kul/.rvm/gems/ruby-2.4.1/gems/ransack-1.8.7/lib/ransack.rb:5:in `<top (required)>'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/kul/mygem/app/turbosack-2-241514/config/application.rb:17:in `<top (required)>'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `require'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `block in perform'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /Users/kul/mygem/app/turbosack-2-241514/config/application.rb:17:in `<top (required)>'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `require'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `block in perform'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
	from /Users/kul/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by kul1** [comment]
OK I found error:
I supposed to finish install mongodb before add ransack gem.
Once installed mongodb my rails can start with no error above 
Thanks

**Comment by kul1** [comment]
First I thought it was -B -O -T option for mongodb instead of activerecord.
But still even with or with out that option still the same error. 
I will run all a few test before any comment.
The gemfile is good it run rails s without the gem 'ransack' and broke once install the gem.

**Comment by gregmolnar** [comment]
@kul1 Ransack should be after the mongoid gem in the Gemfile.

**Comment by paulmakepeace** [comment]
FWIW, it was [validates_hostname](https://rubygems.org/gems/validates_hostname) that had to be put above ransack (Rails 4)
