### ISSUE TITLE
Polymorphic search, default scope and JoinDependency error.

### ISSUE THREAD

**Issue by jozefvaclavik** [activerecord-hackery/ransack#918]
I have polymorphic association that I try to search on. We're still on rails 4.0 and have default scope that complicates things (on one of our models we have `default_scope {where(deleted: true)}`. Rails 4.x (until 5.x) has a bug that even if you specify `unscoped`, it will still return scoped in relationship. To load unscoped association, we had to be more specific and for that one `ScopedModel` we had to return `where`.

```
belongs_to :relationable, -> (c) { c.relationable_type == 'ScopedModel' ? where(deleted: [true, false]) : where({}) }, polymorphic: true
```

This all works fine, until I tried to search 
```
= f.search_field :relationable_of_Something_type_field_or_relationable_of_ScopedModel_type_field_eq
```
Then I'm getting
```
12:56:28 web.1          | NoMethodError - undefined method `relationable_type' for #<ActiveRecord::Associations::JoinDependency::JoinAssociation:0x007f9961a09c98>:
12:56:28 web.1          |   affiliate/app/models/my_model.rb:10:in `block in <class:MyModel>'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/associations/join_dependency/join_association.rb:113:in `block (2 levels) in join_to'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/associations/join_dependency/join_association.rb:111:in `block in join_to'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/associations/join_dependency/join_association.rb:74:in `join_to'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation/query_methods.rb:971:in `block in build_joins'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation/query_methods.rb:970:in `build_joins'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation/query_methods.rb:815:in `build_arel'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation/query_methods.rb:808:in `arel'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation.rb:608:in `references_eager_loaded_tables?'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation.rb:522:in `eager_loading?'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation.rb:587:in `exec_queries'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation.rb:471:in `load'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation.rb:220:in `to_a'
12:56:28 web.1          |   activerecord (4.0.13) lib/active_record/relation/delegation.rb:12:in `each'
12:56:28 web.1          |   affiliate/app/views/controller/index.html.erb:41:in `block in _app_views_controller_index_html_erb__3389702280867044960_70148367811920'
```

The easy fix is to
```
belongs_to :relationable, -> (c) { c.try(:relationable_type) == 'ScopedModel' ? where(deleted: [true, false]) : where({}) }, polymorphic: true
```
as `c` is not my model class, but `JoinAssociation` instead. But then it search with default scope and doesn't return results out of default scope.

Before you ask, unfortunately we cannot remove default scope, nor update to rails 5.x that easy.

Any ideas what to return in that lambda when `c` is `JoinAssociation` so it expands scope?

I'm on `ransack (1.8.2)`

**Comment by seanfcarroll** [comment]
Sorry we are not supporting Rails 4.0 anymore.
