### ISSUE TITLE
Broken with Rails 5.2.1

### ISSUE THREAD

**Issue by pedrofurtado** [activerecord-hackery/ransack#942]
When I upgrade to Rails 5.2.1, the following error appears:

```
wrong number of arguments (given 4, expected 3)

activerecord (5.2.1) lib/active_record/associations/join_dependency.rb:70:in `initialize'
LINE WITH ERROR --->  ransack (1.8.8) lib/ransack/adapters/active_record/context.rb:294:in `new'
ransack (1.8.8) lib/ransack/adapters/active_record/context.rb:294:in `build_joins'
ransack (1.8.8) lib/ransack/adapters/active_record/context.rb:247:in `join_dependency'
ransack (1.8.8) lib/ransack/adapters/active_record/ransack/context.rb:27:in `initialize'
ransack (1.8.8) lib/ransack/adapters/active_record/context.rb:16:in `initialize'
ransack (1.8.8) lib/ransack/adapters/active_record/ransack/context.rb:11:in `new'
ransack (1.8.8) lib/ransack/adapters/active_record/ransack/context.rb:11:in `for_class'
ransack (1.8.8) lib/ransack/context.rb:22:in `for'
ransack (1.8.8) lib/ransack/search.rb:25:in `initialize'
ransack (1.8.8) lib/ransack/adapters/active_record/base.rb:17:in `new'
ransack (1.8.8) lib/ransack/adapters/active_record/base.rb:17:in `ransack'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sentry-raven (2.7.4) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.1) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.1) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
.....
```

This method of ActiveRecord changed, and the ransack + polyamorous broken with it.

**Comment by gregmolnar** [comment]
Just point your gemfile to ransack's master till the next release.
