### ISSUE TITLE
Rails 6 compatibility

### ISSUE THREAD

**Issue by lazaronixon** [activerecord-hackery/ransack#999]
```
ActionView::Template::Error (unable to convert unpermitted parameters to hash):

<th><%= sort_link(@q, :name) %></th>
  
actionpack (6.0.0.beta1) lib/action_controller/metal/strong_parameters.rb:274:in `to_h' 
actionpack (6.0.0.beta1) lib/action_dispatch/routing/url_for.rb:179:in `full_url_for' 
actionpack (6.0.0.beta1) lib/action_dispatch/routing/url_for.rb:170:in `url_for' 
actionview (6.0.0.beta1) lib/action_view/routing_url_for.rb:93:in `url_for' 
ransack (50ef94f9f184) lib/ransack/helpers/form_helper.rb:94:in `url' 
ransack (50ef94f9f184) lib/ransack/helpers/form_helper.rb:54:in `sort_link' 
app/views/users/index.html.erb:12 
```

**Comment by gregmolnar** [comment]
Since we rely on private APIs it doesn't make sense to work on compatibility before at least an RC version.

**Comment by gregmolnar** [comment]
This one is fixed by https://github.com/activerecord-hackery/ransack/pull/1001
